In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [7]:
df['Spam'] = df['Category'].apply(lambda x: 1 if x == 'spam' else 0)

In [8]:
df.head()

Category                                            Message  Spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.Spam, test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [15]:
X_test.shape

(1115,)

In [18]:
X_train[:4]

237     Or ill be a little closer like at the bus stop...
3573                 Yup, leaving right now, be back soon
4341    I want to sent  &lt;#&gt; mesages today. Thats...
3032    gonna let me know cos comes bak from holiday t...
Name: Message, dtype: object

In [19]:
X_train[:4][4341]

'I want to sent  &lt;#&gt; mesages today. Thats y. Sorry if i hurts'

In [20]:
type(y_train)

pandas.core.series.Series

In [21]:
y_train[:4]

237     0
3573    0
4341    0
3032    0
Name: Spam, dtype: int64

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
v = CountVectorizer()

X_train_cv =  v.fit_transform(X_train.values)
X_train_cv

<4457x7738 sparse matrix of type '<class 'numpy.int64'>'
	with 58616 stored elements in Compressed Sparse Row format>

In [25]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
X_train_cv.shape

(4457, 7738)

In [28]:
v.get_feature_names_out()[1000:1060]

array(['any', 'anybody', 'anyhow', 'anymore', 'anyone', 'anyones',
       'anythiing', 'anythin', 'anything', 'anythingtomorrow', 'anytime',
       'anyway', 'anyways', 'anywhere', 'apart', 'apartment', 'apes',
       'apeshit', 'aphex', 'apnt', 'apo', 'apologise', 'apologize',
       'apology', 'app', 'apparently', 'appeal', 'appear',
       'applausestore', 'applebees', 'apples', 'application', 'apply',
       'applyed', 'applying', 'appointment', 'appointments', 'appreciate',
       'appreciated', 'approaches', 'approaching', 'appropriate',
       'approve', 'approved', 'approx', 'apps', 'appt', 'appy', 'april',
       'aproach', 'apt', 'aptitude', 'aquarius', 'ar', 'arabian',
       'arcade', 'ard', 'are', 'area', 'aren'], dtype=object)

In [29]:
v.get_feature_names_out().shape

(7738,)

In [30]:
v.vocabulary_

{'or': 4981,
 'ill': 3630,
 'be': 1284,
 'little': 4171,
 'closer': 1876,
 'like': 4131,
 'at': 1123,
 'the': 6823,
 'bus': 1594,
 'stop': 6510,
 'on': 4946,
 'same': 5903,
 'street': 6529,
 'yup': 7724,
 'leaving': 4084,
 'right': 5795,
 'now': 4859,
 'back': 1201,
 'soon': 6334,
 'want': 7382,
 'to': 6941,
 'sent': 6028,
 'lt': 4272,
 'gt': 3282,
 'mesages': 4473,
 'today': 6948,
 'thats': 6822,
 'sorry': 6342,
 'if': 3619,
 'hurts': 3583,
 'gonna': 3208,
 'let': 4106,
 'me': 4424,
 'know': 3981,
 'cos': 2052,
 'comes': 1937,
 'bak': 1212,
 'from': 3046,
 'holiday': 3492,
 'that': 6819,
 'day': 2217,
 'is': 3771,
 'coming': 1941,
 'don': 2443,
 't4get2text': 6682,
 'number': 4872,
 'urgent': 7208,
 'your': 7706,
 'mobile': 4564,
 'has': 3370,
 'been': 1307,
 'awarded': 1177,
 'with': 7553,
 '2000': 347,
 'prize': 5433,
 'guaranteed': 3286,
 'call': 1629,
 '09061790126': 209,
 'land': 4024,
 'line': 4145,
 'claim': 1845,
 '3030': 429,
 'valid': 7250,
 '12hrs': 291,
 'only': 4954,
 '15

In [43]:
X_train_np = X_train_cv.toarray()

In [44]:
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
X_train[:4][237]

'Or ill be a little closer like at the bus stop on the same street'

In [51]:
v.get_feature_names_out()[1771]

'cheaper'

In [52]:
v.vocabulary_

{'or': 4981,
 'ill': 3630,
 'be': 1284,
 'little': 4171,
 'closer': 1876,
 'like': 4131,
 'at': 1123,
 'the': 6823,
 'bus': 1594,
 'stop': 6510,
 'on': 4946,
 'same': 5903,
 'street': 6529,
 'yup': 7724,
 'leaving': 4084,
 'right': 5795,
 'now': 4859,
 'back': 1201,
 'soon': 6334,
 'want': 7382,
 'to': 6941,
 'sent': 6028,
 'lt': 4272,
 'gt': 3282,
 'mesages': 4473,
 'today': 6948,
 'thats': 6822,
 'sorry': 6342,
 'if': 3619,
 'hurts': 3583,
 'gonna': 3208,
 'let': 4106,
 'me': 4424,
 'know': 3981,
 'cos': 2052,
 'comes': 1937,
 'bak': 1212,
 'from': 3046,
 'holiday': 3492,
 'that': 6819,
 'day': 2217,
 'is': 3771,
 'coming': 1941,
 'don': 2443,
 't4get2text': 6682,
 'number': 4872,
 'urgent': 7208,
 'your': 7706,
 'mobile': 4564,
 'has': 3370,
 'been': 1307,
 'awarded': 1177,
 'with': 7553,
 '2000': 347,
 'prize': 5433,
 'guaranteed': 3286,
 'call': 1629,
 '09061790126': 209,
 'land': 4024,
 'line': 4145,
 'claim': 1845,
 '3030': 429,
 'valid': 7250,
 '12hrs': 291,
 'only': 4954,
 '15

In [53]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [54]:
np.where(X_train_np[0]!=0)

(array([1123, 1284, 1594, 1876, 3630, 4131, 4171, 4946, 4981, 5903, 6510,
        6529, 6823], dtype=int64),)

In [59]:
X_train[::][3630]

'Should I head straight there or what'

In [57]:
X_train_np[0][3630]

1

In [60]:
from sklearn.naive_bayes import MultinomialNB

In [61]:
model = MultinomialNB()

In [62]:
model.fit(X_train_cv, y_train)

MultinomialNB()

In [63]:
X_test_cv = v.transform(X_test)

In [67]:
from sklearn.metrics import classification_report

In [69]:
y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       954
           1       0.99      0.95      0.97       161

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [76]:
email = ['''
Being the ninth person and the first and only woman to hold the position I deposited the sum of USD$30.5M (Thirty Million Five Hundred Thousand U.S. Dollars) with Standard/bank of South Africa presently. These funds emanated as a result of an over-invoiced contract which I executed with the Reserve Bank. Though I am the person who approved this contract, I honestly never knew at the time that it had been over invoiced. I am now afraid that the government of South Africa might start to investigate the contracts I awarded; presently this money is still with the bank here in South Africa. I suffer from cancer and recently my Doctor informed me that due to my old age I would not be able to stay alive past the next six months due to the cancer. Nonetheless what disturbs me mostly is the stroke I suffered. Having known my condition I decided to donate these funds to a church or better still a Christian individual that will utilize this money the way I am going to instruct here. I want an individual person or church organization that will use the funds for churches, orphanages, research centers and widows propagating the word of God and to ensure that the house of God is maintained.

''',
'''
Hi Aryan, 

Hope you have gone through the website link and have an idea of what we are doing

Need the following to be done:

1. Hospitals - Need the write up to be put into chat GPT and refreshed in Language and put into excel format as sent on whats app. This would mean approx 20 hospitals / cities. 
2. Doctors - Need the Doc - approx 10 per hospital to be again put into excel format for uploading into the website. 

as we expand we shall contine to get data like this. 

Kindly inform the cost that you would charge for doing the same. 

This is urgent since i need this uploaded onto the website within this week. 
Once we have firmed up i can give you the data on a pen drive. 

Regards
''']

In [77]:
email_count = v.transform(email)

In [78]:
model.predict(email_count)

array([0, 0], dtype=int64)

In [79]:
from sklearn.pipeline import Pipeline

In [80]:
clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [81]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [83]:
y_pred = clf.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       954
           1       0.99      0.95      0.97       161

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115

